### ISSUE TITLE
Rake test don't execute

### ISSUE THREAD

**Issue by lucca65** [Cendrao/ruby-fizzbuzz#2]
When trying to run `rake test` I get the following error:

```
╰─± rake test
/Users/Lucca/.rvm/rubies/ruby-2.2.3/bin/ruby -I"lib:test"  "/Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/fizzbuzz_test.rb" 
/Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- test/unit (LoadError)
    from /Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/Lucca/Development/ruby/scripts/ruby-fizzbuzz/test/fizzbuzz_test.rb:1:in `<top (required)>'
    from /Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
    from /Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
    from /Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test"  "/Users/Lucca/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/fizzbuzz_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

Maybe something related to dependencies?

**Comment by lucca65** [comment]
Try to understand why so many places people run

```
bundle exec rake test
```

instead of:

```
rake test
```

**Comment by Cendrao** [comment]
I think I got it.

`bundle exec` will execute commands with the dependencies specified in my gemfile. 

It makes somes changes in the environment too, like add executables directories to $PATH.

By doing `bundle exec rake test` I guarantee that all gems will be in the right version too
